### ISSUE TITLE
Suggestion: Instead of leaving cursor where it is, place it on the end of the line.

### ISSUE THREAD

**Issue by FooqX** [onolox/smartsemicolonidea#2]
I have a suggestion - instead of leaving cursor where it is, place it on the end of the line just like shown in video.
You can make an option, to insert a new line below the current cursor and put the cursor at the beginning of the new line on a semicolon key.
![basic_feature](https://user-images.githubusercontent.com/65967000/145714927-ae4abf6e-26e4-4bcc-accb-ad5f0174d39a.gif)

**Comment by onolox** [comment]
There's an shortcut for this: Ctrl+ Shift + enter.
